### ISSUE TITLE
Make skip_repair_examplars skip all examplars?

### ISSUE THREAD

**Issue by arnaudon** [BlueBrain/BluePyMM#226]
@alex4200 noticed that if we don't have the exemplar morphs in the morph release MM complains even with skip_repair_examplars:

https://github.com/BlueBrain/BluePyMM/blob/master/bluepymm/prepare_combos/create_mm_sqlite.py#L118

maybe we can move this if further up to not even try to load repaired exemplar?

**Comment by wvangeit** [comment]
do we know where it complains exactly?

**Comment by arnaudon** [comment]
Here: https://github.com/BlueBrain/BluePyMM/blob/master/bluepymm/prepare_combos/create_mm_sqlite.py#L136

**Comment by wvangeit** [comment]
Isn't that line 'protected' by skip_repair_examplars?

**Comment by arnaudon** [comment]
my bad, this one: https://github.com/BlueBrain/BluePyMM/blob/master/bluepymm/prepare_combos/create_mm_sqlite.py#L115

**Comment by wvangeit** [comment]
Ok, but so that's a different case, i.e. it checks the 'unrepaired' morph. Imo this morph should always be available, so that we can test a run with the original morphology. The skip_repair_examplars is just there in case the unrepaired examplar is not sure to survive the repair process (which is not guaranteed).

**Comment by arnaudon** [comment]
Ah yes, you are right. Indeed, the issue was that @alex4200 tests had missing exemplars, so it was crashing here. I agree we should have these morphs available, but I naively thought that this option would also not require them. All cleared then! Thanks!
